[package]
name = "sulfite"
version = "0.0.13"
edition = "2024"
authors = ["Terence Liu <terence@tnhcdata.io>"]
description = "A high-level S3 client built on AWS SDK for Rust for bandwidth saturation"
license = "MIT"
homepage = "https://github.com/tnhcdata/sulfite"
repository = "https://github.com/tnhcdata/sulfite"
readme = "README.md"
keywords = ["s3", "object", "storage"]
categories = ["web-programming::http-client"]

[dependencies]
aws-config = { version = "1.5", features = ["behavior-version-latest"] }
aws-credential-types = { version = "1.2", features = ["hardcoded-credentials"] }
aws-sdk-s3 = { version = "1.30", default-features = false, features = ["rt-tokio", "default-https-client", "http-1x", "sigv4a"] }
bytes = "1"
filetime = "0.2"
futures = "0.3"
rand = "0.10"
tokio = { version = "1", features = ["full"] }
tokio-retry = "0.3"
thiserror = "2"
tracing = { version = "0.1", features = ["log"] }
urlencoding = "2.1"

indicatif = { version = "0.18", features = ["tokio"], optional = true }

[features]
default = []
indicatif = ["dep:indicatif"]

[dev-dependencies]
rstest = "0.27"
